import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121414",
        "surface-tint": "#79df00",
        "surface-container-highest": "#343535",
        "on-error": "#690005",
        "primary": "#ffffff",
        "on-background": "#e3e2e2",
        "on-primary-fixed": "#0c2000",
        "secondary-container": "#4a4949",
        "on-tertiary-fixed-variant": "#474746",
        "on-secondary": "#313030",
        "inverse-primary": "#376b00",
        "tertiary-fixed-dim": "#c8c6c5",
        "error": "#ffb4ab",
        "surface-container-high": "#292a2a",
        "primary-container": "#8afe00",
        "primary-fixed": "#8afe00",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#474646",
        "inverse-surface": "#e3e2e2",
        "surface-container-low": "#1b1c1c",
        "surface-container-lowest": "#0d0e0f",
        "surface-bright": "#383939",
        "on-primary-fixed-variant": "#285000",
        "outline": "#89957a",
        "surface-container": "#1f2020",
        "secondary": "#c9c6c5",
        "on-primary-container": "#3b7100",
        "surface-dim": "#121414",
        "surface-variant": "#343535",
        "on-tertiary": "#313030",
        "tertiary-fixed": "#e5e2e1",
        "inverse-on-surface": "#303031",
        "on-tertiary-container": "#656464",
        "on-tertiary-fixed": "#1c1b1b",
        "on-primary": "#1a3700",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c9c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "outline-variant": "#3f4a34",
        "tertiary": "#ffffff",
        "on-surface-variant": "#becbae",
        "on-surface": "#e3e2e2",
        "primary-fixed-dim": "#79df00",
        "on-secondary-container": "#bab8b7",
        "tertiary-container": "#e5e2e1",
        "error-container": "#93000a",
        "background": "#121414",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "gutter-desktop": "24px",
        "stack-lg": "64px",
        "stack-sm": "16px",
        "margin-mobile": "20px",
        "stack-md": "32px",
        "base": "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Barlow Condensed", "sans-serif"],
        "headline-md": ["Bebas Neue", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Barlow Condensed", "sans-serif"],
        "headline-xl-mobile": ["Bebas Neue", "sans-serif"],
        "display-lg": ["Bebas Neue", "sans-serif"],
        "headline-xl": ["Bebas Neue", "sans-serif"],
        "display": ["Bebas Neue", "sans-serif"],
        "label": ["Barlow Condensed", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["24px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "32px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "600" }],
        "headline-xl-mobile": ["36px", { lineHeight: "36px", fontWeight: "400" }],
        "display-lg": ["80px", { lineHeight: "80px", letterSpacing: "2px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "48px", letterSpacing: "1px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
